runtime: php55
api_version: 1
threadsafe: true

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
- url: /hello/
  static_files: hello/index.html
  upload: hello/index.html

- url: /hello/wasm_exec.js
  static_files: hello/wasm_exec.js
  upload: hello/wasm_exec.js

- url: /hello/hello.wasm
  static_files: hello/hello.wasm
  upload: hello/hello.wasm
  mime_type: application/wasm

- url: /memexport/
  static_files: memexport/index.html
  upload: memexport/index.html

- url: /memexport/wasm_exec.js
  static_files: memexport/wasm_exec.js
  upload: memexport/wasm_exec.js

- url: /memexport/memexport.wasm
  static_files: memexport/memexport.wasm
  upload: memexport/memexport.wasm
  mime_type: application/wasm

- url: /memimport/
  static_files: memimport/index.html
  upload: memimport/index.html

- url: /memimport/wasm_exec.js
  static_files: memimport/wasm_exec.js
  upload: memimport/wasm_exec.js

- url: /memimport/memimport.wasm
  static_files: memimport/memimport.wasm
  upload: memimport/memimport.wasm
  mime_type: application/wasm

- url: /calc/
  static_files: calc/index.html
  upload: calc/index.html

- url: /calc/wasm_exec.js
  static_files: calc/wasm_exec.js
  upload: calc/wasm_exec.js

- url: /calc/calc.wasm
  static_files: calc/calc.wasm
  upload: calc/calc.wasm
  mime_type: application/wasm
